/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author Angelica Guerrero
 */
public class FMenu extends javax.swing.JFrame {

    Color colorFondo = new Color(53, 81, 211);
    public static JDesktopPane jmenu;

    public FMenu() {
        initComponents();
        this.setSize(1366, 768); //minimas dimensiones cuando se oprime el botón maximizar
        this.setTitle("Sistema de muebleria");
        this.setLayout(null);
        jmenu = new JDesktopPane();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jmenu.setBounds(0, 0, ancho, alto); // 
        this.add(jmenu);
    setIconImage(new ImageIcon(getClass().getResource("/Imagenes/iconoM.png")).getImage());
        
        for (Component component : menuBar.getComponents()) {
            if (component instanceof JMenu) {
                JMenu menu = (JMenu) component;
                menu.setOpaque(true);
                menu.setBackground(colorFondo);
                menu.setForeground(Color.WHITE);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1_agregar_usuario = new javax.swing.JMenuItem();
        jMenuItem2_ad_usuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3_agregar_cliente = new javax.swing.JMenuItem();
        jMenuItem4_ad_cliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5_agregar_categoria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7_nuevo_articulo = new javax.swing.JMenuItem();
        jMenuItem8_ad_articulos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9_nueva_venta = new javax.swing.JMenuItem();
        jMenuItem_administrar = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItemAbono = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem3_historial = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu7.setText("jMenu7");
        jMenu7.setPreferredSize(new java.awt.Dimension(140, 50));

        jMenu8.setText("jMenu8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenfondo.png"))); // NOI18N
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 630));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 620));

        menuBar.setBackground(new java.awt.Color(0, 0, 204));
        menuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuBar.setForeground(new java.awt.Color(0, 0, 0));
        menuBar.setBorderPainted(false);
        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBar.setMinimumSize(new java.awt.Dimension(903, 100));
        menuBar.setOpaque(true);
        menuBar.setPreferredSize(new java.awt.Dimension(1000, 90));

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empresario (1).png"))); // NOI18N
        jMenu1.setText("Usuarios");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem1_agregar_usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1_agregar_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario (1).png"))); // NOI18N
        jMenuItem1_agregar_usuario.setText("Agregar usuario");
        jMenuItem1_agregar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_agregar_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1_agregar_usuario);

        jMenuItem2_ad_usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem2_ad_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil.png"))); // NOI18N
        jMenuItem2_ad_usuario.setText("Administrar usuarios");
        jMenuItem2_ad_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_ad_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2_ad_usuario);

        menuBar.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 0, 0));
        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comunidad.png"))); // NOI18N
        jMenu2.setText("Clientes");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem3_agregar_cliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem3_agregar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario (2).png"))); // NOI18N
        jMenuItem3_agregar_cliente.setText("Agregar cliente");
        jMenuItem3_agregar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_agregar_clienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3_agregar_cliente);

        jMenuItem4_ad_cliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem4_ad_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil.png"))); // NOI18N
        jMenuItem4_ad_cliente.setText("Administrar clientes");
        jMenuItem4_ad_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4_ad_clienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4_ad_cliente);

        menuBar.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aplicacion.png"))); // NOI18N
        jMenu4.setText("Categorias");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu4.setMinimumSize(new java.awt.Dimension(170, 50));
        jMenu4.setPreferredSize(new java.awt.Dimension(160, 50));

        jMenuItem5_agregar_categoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem5_agregar_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar (2).png"))); // NOI18N
        jMenuItem5_agregar_categoria.setText("Categorias");
        jMenuItem5_agregar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5_agregar_categoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5_agregar_categoria);

        menuBar.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/muebles.png"))); // NOI18N
        jMenu5.setText("Articulos");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem7_nuevo_articulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem7_nuevo_articulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-producto.png"))); // NOI18N
        jMenuItem7_nuevo_articulo.setText("Nuevo articulo");
        jMenuItem7_nuevo_articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7_nuevo_articuloActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7_nuevo_articulo);

        jMenuItem8_ad_articulos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem8_ad_articulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/producto (1).png"))); // NOI18N
        jMenuItem8_ad_articulos.setText("Administrar articulos");
        jMenuItem8_ad_articulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8_ad_articulosActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8_ad_articulos);

        menuBar.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito-de-compras.png"))); // NOI18N
        jMenu6.setText("Transacciones");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(190, 50));

        jMenuItem9_nueva_venta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem9_nueva_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/anadir-a-la-cesta.png"))); // NOI18N
        jMenuItem9_nueva_venta.setText("Nueva venta");
        jMenuItem9_nueva_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9_nueva_ventaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9_nueva_venta);

        jMenuItem_administrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem_administrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administrar.png"))); // NOI18N
        jMenuItem_administrar.setText("Administrar transaccion");
        jMenuItem_administrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_administrarActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_administrar);

        menuBar.add(jMenu6);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/metodo-de-pago.png"))); // NOI18N
        jMenu9.setText("Abonos y liquidaciones");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu9.setPreferredSize(new java.awt.Dimension(255, 50));

        jMenuItemAbono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemAbono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar (3).png"))); // NOI18N
        jMenuItemAbono.setText("Abono");
        jMenuItemAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbonoActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItemAbono);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprobar.png"))); // NOI18N
        jMenuItem1.setText("Liquidacion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem1);

        menuBar.add(jMenu9);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial-de-transacciones (1).png"))); // NOI18N
        jMenu11.setText("Historial");
        jMenu11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu11.setPreferredSize(new java.awt.Dimension(140, 38));

        jMenuItem3_historial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem3_historial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial-de-transacciones.png"))); // NOI18N
        jMenuItem3_historial.setText("Historial");
        jMenuItem3_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_historialActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem3_historial);

        menuBar.add(jMenu11);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion (1).png"))); // NOI18N
        jMenu10.setText("Cerrar sesión");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu10.setPreferredSize(new java.awt.Dimension(190, 31));

        jMenuItem2.setText("Cerrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem2);

        menuBar.add(jMenu10);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1_agregar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_agregar_usuarioActionPerformed
        // TODO add your handling code here:
        VUsuario usuario = new VUsuario(this);
        jmenu.add(usuario);
        // Hacer visible la ventana interna
        usuario.setVisible(true);
        // Ocultar la imagen de fondo
        ocultarImagenDeFondo();
        // Agregar un InternalFrameAdapter para manejar el evento de cierre de la ventana interna
        usuario.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                super.internalFrameClosing(e);
                mostrarImagenDeFondo(); // Mostrar imagen de fondo al cerrar la ventana interna
            }
        });
    }//GEN-LAST:event_jMenuItem1_agregar_usuarioActionPerformed

    private void jMenuItem5_agregar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5_agregar_categoriaActionPerformed
        // TODO add your handling code here:
        VCategoria categoria = new VCategoria(this);
        jmenu.add(categoria);
        categoria.setVisible(true);
        ocultarImagenDeFondo();
        // Agregar un InternalFrameAdapter para manejar el evento de cierre de la ventana interna
        categoria.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                super.internalFrameClosing(e);
                mostrarImagenDeFondo(); // Mostrar imagen de fondo al cerrar la ventana interna
            }
        });
    }//GEN-LAST:event_jMenuItem5_agregar_categoriaActionPerformed

    private void jMenuItem7_nuevo_articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7_nuevo_articuloActionPerformed
        // TODO add your handling code here:
        VArticulos articulo = new VArticulos(this);
        jmenu.add(articulo);
        articulo.setVisible(true);
        ocultarImagenDeFondo();
        articulo.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                super.internalFrameClosing(e);
                mostrarImagenDeFondo(); // Mostrar imagen de fondo al cerrar la ventana interna
            }
        });
    }//GEN-LAST:event_jMenuItem7_nuevo_articuloActionPerformed

    private void jMenuItem8_ad_articulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8_ad_articulosActionPerformed
        // TODO add your handling code here:
        AdArticulos adArticulo = new AdArticulos(this);
        jmenu.add(adArticulo);
        adArticulo.setVisible(true);
        ocultarImagenDeFondo();
        adArticulo.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                super.internalFrameClosing(e);
                mostrarImagenDeFondo(); // Mostrar imagen de fondo al cerrar la ventana interna
            }
        });
    }//GEN-LAST:event_jMenuItem8_ad_articulosActionPerformed

    private void jMenuItem3_agregar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_agregar_clienteActionPerformed
        // TODO add your handling code here:
        VCliente cliente = new VCliente(this);
        jmenu.add(cliente);
        cliente.setVisible(true);
        ocultarImagenDeFondo();
        cliente.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                super.internalFrameClosing(e);
                mostrarImagenDeFondo(); // Mostrar imagen de fondo al cerrar la ventana interna
            }
        });
    }//GEN-LAST:event_jMenuItem3_agregar_clienteActionPerformed

    private void jMenuItem9_nueva_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9_nueva_ventaActionPerformed
        // TODO add your handling code here:
        VTransaccion transaccion = new VTransaccion(this);
        jmenu.add(transaccion);
        transaccion.setVisible(true);
        ocultarImagenDeFondo();
        transaccion.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                super.internalFrameClosing(e);
                mostrarImagenDeFondo(); // Mostrar imagen de fondo al cerrar la ventana interna
            }
        });
    }//GEN-LAST:event_jMenuItem9_nueva_ventaActionPerformed

    private void jMenuItem_administrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_administrarActionPerformed
        // TODO add your handling code here:
        AdTransaccion adTransaccion = new AdTransaccion(this);
        jmenu.add(adTransaccion);
        adTransaccion.setVisible(true);
        ocultarImagenDeFondo();
        adTransaccion.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                super.internalFrameClosing(e);
                mostrarImagenDeFondo(); // Mostrar imagen de fondo al cerrar la ventana interna
            }
        });
    }//GEN-LAST:event_jMenuItem_administrarActionPerformed

    private void jMenuItem4_ad_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4_ad_clienteActionPerformed
        // TODO add your handling code here:
        AdCliente adcliente = new AdCliente(this);
        jmenu.add(adcliente);
        adcliente.setVisible(true);
        ocultarImagenDeFondo();
        adcliente.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                super.internalFrameClosing(e);
                mostrarImagenDeFondo(); // Mostrar imagen de fondo al cerrar la ventana interna
            }
        });
    }//GEN-LAST:event_jMenuItem4_ad_clienteActionPerformed

    private void jMenuItem2_ad_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_ad_usuarioActionPerformed
        // TODO add your handling code here:
        AdUsuario adusuario = new AdUsuario(this);
        jmenu.add(adusuario);
        adusuario.setVisible(true);
        ocultarImagenDeFondo();
        adusuario.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                super.internalFrameClosing(e);
                mostrarImagenDeFondo(); // Mostrar imagen de fondo al cerrar la ventana interna
            }
        });
    }//GEN-LAST:event_jMenuItem2_ad_usuarioActionPerformed

    private void jMenuItemAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbonoActionPerformed
        // TODO add your handling code here:
        VAbono abono = new VAbono(this);
        jmenu.add(abono);
        abono.setVisible(true);
        ocultarImagenDeFondo();
        abono.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                super.internalFrameClosing(e);
                mostrarImagenDeFondo(); // Mostrar imagen de fondo al cerrar la ventana interna
            }
        });
    }//GEN-LAST:event_jMenuItemAbonoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        VLiquidacion liquidacion = new VLiquidacion(this);
        jmenu.add(liquidacion);
        liquidacion.setVisible(true);
        ocultarImagenDeFondo();
        liquidacion.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                super.internalFrameClosing(e);
                mostrarImagenDeFondo(); // Mostrar imagen de fondo al cerrar la ventana interna
            }
        });
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_historialActionPerformed
        // TODO add your handling code here:
        VHistorial historial=new VHistorial(this);
        jmenu.add(historial);
        historial.setVisible(true);
        ocultarImagenDeFondo();
        historial.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                super.internalFrameClosing(e);
                mostrarImagenDeFondo(); // Mostrar imagen de fondo al cerrar la ventana interna
            }
        });
    }//GEN-LAST:event_jMenuItem3_historialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem1_agregar_usuario;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem2_ad_usuario;
    private javax.swing.JMenuItem jMenuItem3_agregar_cliente;
    private javax.swing.JMenuItem jMenuItem3_historial;
    private javax.swing.JMenuItem jMenuItem4_ad_cliente;
    private javax.swing.JMenuItem jMenuItem5_agregar_categoria;
    private javax.swing.JMenuItem jMenuItem7_nuevo_articulo;
    private javax.swing.JMenuItem jMenuItem8_ad_articulos;
    private javax.swing.JMenuItem jMenuItem9_nueva_venta;
    private javax.swing.JMenuItem jMenuItemAbono;
    private javax.swing.JMenuItem jMenuItem_administrar;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
    public void mostrarImagenDeFondo() {
        if (jLabel1.getIcon() != null) {
            ImageIcon icon = (ImageIcon) jLabel1.getIcon();
            icon.getImage().flush();
            jLabel1.setIcon(null);
        }
        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/imagenfondo.png"));
        jLabel1.setIcon(icon);
        jLabel1.setVisible(true);
        panel1.setVisible(true);
  
    }

    public void ocultarImagenDeFondo() {
        jLabel1.setVisible(false);
        panel1.setVisible(false);
        if (jLabel1.getIcon() != null) {
            ImageIcon icon = (ImageIcon) jLabel1.getIcon();
            icon.getImage().flush();
        }
        
    }
    
}
